config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # List: index, show, new, create
  # Bookmark: new, create, delete
  root to: "lists#index"

  resources :lists, only: [:index, :show, :new, :create] do
    resources :bookmarks, only: [:new, :create]
  end
  resources :bookmarks, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :comment, length: { minimum: 6 }
   validates :movie, uniqueness: { scope: :list }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks
  has_many :movies, through: :bookmarks, dependent: :destroy

  has_many_attached :photos

  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks

  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
    @list = List.find(params[:id])
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @list = List.find(params[:list_id])
    @bookmark.list = @list

    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @list = @bookmark.list_id
    @bookmark.destroy
    redirect_to list_path(@list)
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
    @bookmark = Bookmark.new
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)

    if @list.save
      redirect_to @list, notice: 'Successfully created new List'
    else
      render :new
    end
  end

  private

  def list_params
    params.require(:list).permit(:name, photos: [])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/new.html.erb
<h1>Wow.. new bookmark</h1>
<%= simple_form_for [@list, @bookmark] do |f| %>
  <%= f.input :comment, as: :text %>
  <%= f.association :movie %>
  <%= f.button :submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class='bg-white'>
    <%= yield %>
  </body>
</html>

app/views/lists/_navbar.html.erb
<nav class="navbar navbar-dark bg-dark navbar-expand-lg navbar-light bg-light ">
<div class="container">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse d-flex justify-content-center" id="navbarNav">
  <div class="row">
    <ul class="navbar-nav">
      <li class="nav-item">
        <%= link_to "All lists", root_path, class: 'nav-link' %>
      </li>
    </ul>
  </div>
  </div>
</div>
</nav>

app/views/lists/index.html.erb
<%= render 'navbar' %>
<div class="container">
<div class="title">
      <h1 class="">your lists</h1>
      <%= link_to "Create new list", new_list_path, class: 'create-btn' %>
</div>
      <div class="cards">
        <% @lists.each do |list| %>
        <div class="grid-card" style="width: 18rem;">
          <% if list.photos.attached? %>
            <%= cl_image_tag list.photos[0].key, height: 300, width: 400, crop: :fill, class: 'card-img-top' %>
          <% end %>
            <h2><%= link_to list.name, list_path(list.id), class: 'list-link title' %></h2>
        </div>
      <% end %>
      </div>
    </div>
</div>

app/views/lists/new.html.erb
<h1>Create new list</h1>
<%= simple_form_for(@list) do |f| %>
  <%= f.input :name %>
  <%= f.input :photos, as: :file, input_html: { multiple: true } %>
  <%= f.button :submit%>
<% end %>

app/views/lists/show.html.erb
<%= render 'navbar' %>
<div class="grid-container">
<div class="title">
<h1><%= @list.name %></h1>
</div>
<div class="w-50 mx-auto">
<%= simple_form_for [@list, @bookmark] do |f| %>
  <%= f.input :comment, as: :text, class: 'input-field' %>
  <%= f.association :movie, class: 'input-field' %>
  <%= f.button :submit, class: 'submit-btn' %>
<% end %>
</div>

<% @list.bookmarks.each do |bookmark| %>
  <div class="list-card-item mx-auto">
  <div>
    <p><%= bookmark.comment %></p>
    <h3><%= bookmark.movie.title %></h3>
  </div>
    <%= link_to "delete bookmark", bookmark_path(bookmark), method: :delete,
              data: { confirm: "Are you sure?" }, class: 'delete-btn'  %>
  </div>
<% end %>

<% if @list.photos.attached? %>
  <% @list.photos.each do |photo| %>
      <%= cl_image_tag photo.key, height: 300, width: 400, crop: :fill %>
  <% end %>
<% end %>

</div>